# render.yaml
services:
  - type: web
    name: alert-now
    runtime: python-3.12
    build:
      - pip install --upgrade pip setuptools wheel
      - pip install -r requirements.txt
    env: python
    entrypoint: "gunicorn -w 4 -k eventlet -b 0.0.0.0:$PORT AlertNow:app"
    plan: free
