# render.yaml
services:
  - type: web
    name: alert-now
    pythonVersion: "3.13"
    runtime: python-3.13
    build:
      - pip install --upgrade pip setuptools wheel
      - pip install -r requirements.txt
    buildCommand: "./build.sh"
    env: python
    entrypoint: "gunicorn -w 4 -k eventlet -b 0.0.0.0:$PORT AlertNow:app"
    plan: free
