services:
  - type: web
    name: alert-now
    runtime: python-3.13
    build:
      - pip install --upgrade pip setuptools wheel
      - pip install -r requirements.txt
    env: python
    plan: free
    command: python AlertNow.py